### ISSUE TITLE
Result is differ from vcftools

### ISSUE THREAD

**Issue by q623928815** [simonhmartin/genomics_general#10]
Its a very good tools. but I use genomics_general and vcftools process the same vcf data with same parameter(window=50K,step=10K), they give me different PI and FST. I'm confused, why it happened?
I convert the vcf file to geno file without any filter.
Need your help, Thanks.

**Comment by simonhmartin** [comment]
I am not sure how pi and Fst are computed in vcftools. It is likely that the main difference results from different ways in which missing genotypes are treated. My approach is to exclude missing genotypes on a pair-by-pair basis. Another possible difference is what is considered an invariant site. In my scripts the invariants need to be included in the input file. Missing sites are ignored and are not considered as invariant. It may be that other software automatically assumes that all sites not provided in the input file are invariant.
There are many different ways to compute Fst. My scripts use the "Kst" of Hudson (1992, MBE), but with a modification to account for missing genotypes on a pair-by-pair basis.

If you really want to get to the bottom of this, I recommend making a dummy file with all invariant sites included and no missing data and then compare the results.

**Comment by q623928815** [comment]
Oh, I see. thanks a lot.
after using vcf contains all sites,I got a result which is very similar with vcftools's result.
