### ISSUE TITLE
filterGenotypes does not accept 'randomAlleles' as an output format

### ISSUE THREAD

**Issue by dcmain** [simonhmartin/genomics_general#100]
Hi Simon. I realize that in typical cases you would not want to assign haplotypes randomly to biallelic data because the different alleles might have distinct ancestries and you would bias tip relationships by collapsing biallelic data into randomAlleles but my dataset is a species level dataset, not a population level dataset. I am trying to use your sliding windows pipeline to generate trees to later reconcile in Astral but the biallelic tips make it rather convoluted. Because my individuals are separated by species-level differences, I am not overly concerned about randomly assigning alleles to produce my species tree but when I use the flag -of randomAlleles, it gives an error saying that 'randomAlleles' is not an option. Is the 'randomAlleles' option new? Perhaps my version of genomics general needs updating?

**Comment by simonhmartin** [comment]
Yeah I agree this sounds like a sensible use case. I think the issue is simply that the xcommand should be `-of randomAllele` (without the s).

**Comment by dcmain** [comment]
Thanks for the swift response Simon! I will try that and let you know if I manage to get it to work!

**Comment by dcmain** [comment]
Hi Simon, I just tried running it with -of randomAllele and I got this error:


Create variables for filterGenotypes.py
Run filterGenotypes.py
usage: filterGenotypes.py [-h] [-i INFILE] [-o OUTFILE] [-t THREADS]
                          [--verbose] [-if {phased,diplo,alleles}]
                          [-of {phased,diplo,bases,alleles,coded,count}]
                          [--alleleOrder {freq}] [-s SAMPLES]
                          [--excludeSamples EXCLUDESAMPLES]
                          [-p popName [[samples] ...]] [--popsFile POPSFILE]
                          [--keepAllSamples] [--ploidy PLOIDY [PLOIDY ...]]
                          [--ploidyFile PLOIDYFILE] [--forcePloidy]
                          [--partialToMissing]
                          [--include INCLUDE [INCLUDE ...]]
                          [--includeFile INCLUDEFILE]
                          [--exclude EXCLUDE [EXCLUDE ...]]
                          [--excludeFile EXCLUDEFILE] [--minCalls integer]
                          [--minAlleles integer]
                          [--maxAlleles integer or 'inf']
                          [--minVarCount integer] [--maxHet proportion]
                          [--minFreq freqency] [--maxFreq frequency]
                          [--HWE P-value 'top'/'bottom'/'both']
                          [--minPopCalls MINPOPCALLS [MINPOPCALLS ...]]
                          [--minPopAlleles MINPOPALLELES [MINPOPALLELES ...]]
                          [--maxPopAlleles MAXPOPALLELES [MAXPOPALLELES ...]]
                          [--fixedDiffs] [--nearlyFixedDiff NEARLYFIXEDDIFF]
                          [--thinDist integer] [--podSize PODSIZE]
                          [--noPrecomp] [--noTest]
filterGenotypes.py: error: argument -of/--outputGenoFormat: invalid choice: 'randomAllele' (choose from 'phased', 'diplo', 'bases', 'alleles', 'coded', 'count')

It seems like it doesn't accept 'randomAllele' as an option?

**Comment by simonhmartin** [comment]
This is strange. Do you have the latest version? Line 134 should read
```
                    choices = ("phased","diplo","bases","alleles","randomAllele","coded","count"), help="Genotype format for output")
```
You will also need the latest version of genomics.py for this option to wok.

**Comment by dcmain** [comment]
Thanks so much! Didn't realise that my version was out of date, I just updated and it works now!

**Comment by simonhmartin** [comment]
Great! No worries.
