### ISSUE TITLE
In the results of popgenWindows.py, Dxy > Fst

### ISSUE THREAD

**Issue by yangwukaidi** [simonhmartin/genomics_general#101]
Hi Simon. 
I have a problem that bothers me.
In my results of popgenWindows.py, all the values of Dxy are greater than Fst, as shown below:
![1694007906525](https://github.com/simonhmartin/genomics_general/assets/127917612/922b263c-b2a2-4ee5-93b4-ad0743c188cc)
This was the case across all four populations. 
Why does this happen?
Are these results correct?

**Comment by simonhmartin** [comment]
This looks like the same issue that has been addressed here before:
https://github.com/simonhmartin/genomics_general/issues/22
https://github.com/simonhmartin/genomics_general/issues/87

**Comment by yangwukaidi** [comment]
Hi Simon, thank you.I got it.
