### ISSUE TITLE
ABBABABAwindows.py "TypeError: slidingCoordWindows()"

### ISSUE THREAD

**Issue by ljchueca** [simonhmartin/genomics_general#105]
Hi all,
I'm encountering an issue while running ABBABABAwindows.py, and I need some assistance in resolving it.

 I'm running the following command (python 3.7.4):
   
   ```shell
   ABBABABAwindows.py -w 30000 -m 30 -s 30000 -g ${FILE}.geno.gz \
      -o ${FILE}.fd.Crug.CuSWA.Ccon.Ccav.csv.gz \
      -f phased --minData 0.5 --writeFailedWindow \
      -P1 Crug -P2 CuSWA -P3 Ccon -O Ccav \
      --popsFile Candidula_species_pop -T 60
```

The script is expected to run without any errors, but it returns the following error message:

6264 scaffolds will be analyzed.
Traceback (most recent call last):
File "/ABBABABAwindows.py", line 321, in <module>
    exclude = scafsToExclude)
TypeError: slidingCoordWindows() got an unexpected keyword argument 'headerLine'

I haven't specified any scaffold to exclude. The error seems to be related to the 'headerLine' argument.

I would appreciate any insights, tips, or solutions to this issue.

Thank you in advance for your help.

**Comment by simonhmartin** [comment]
Hi, this appears to be an issue with the version of genomics.py you have. Try re-downloading the entire repository. 
Simon

**Comment by ljchueca** [comment]
> Hi, this appears to be an issue with the version of genomics.py you have. Try re-downloading the entire repository. Simon

I did it and It worked correctly.
Many thanks,
Luis
