### ISSUE TITLE
parseVCF.py bug?

### ISSUE THREAD

**Issue by angusdavison** [simonhmartin/genomics_general#113]
Hi Simon, I was able to get parseVCF.py working on my old machine but not our HPC, producing the following error:

Traceback (most recent call last):
  File "parseVCF.py", line 351, in <module>
    headData = parseHeaderLines(inFile)
  File "parseVCF.py", line 199, in parseHeaderLines
    contigDataDict = dict([x.split("=", maxsplit=1) for x in re.split('<|>', line)[1].split(",")])

The original script at L199 of parseVCF.py is

x.split("=", maxsplit=1)

I changed that to 

x.split("=", 1)

And it works! Of course, not sure why the original worked on one computer but not the other ....

**Comment by simonhmartin** [comment]
Hi Angus, thanks for the note. This is just a python version issue. Older versions of python did not have a 'keyword' assigned to the second argument in the `split()` function, and newer versions (apparently from python 3.3 onward), allow the keyword `maxsplit`, which just makes the code easier to read.
