### ISSUE TITLE
Question about distMat.py

### ISSUE THREAD

**Issue by mylena-s** [simonhmartin/genomics_general#123]
Hello Simon!

Thank you a lot for sharing these tools. They are super useful

I have a really simple/dumb question regarding distMat.py. What distance statistic does it calculate? Is it just number of substitutions per window? 

Thanks

Mylena

**Comment by simonhmartin** [comment]
Hi Mylena,

The distance is simply the number of differences divided by the total number of aligned sites between each pair, taking missing data into account. For diploid individuals, the distance reported is equivalent to the average pairwise distance between the four possible pairs of haplotypes, taking one from each individual. This is equivalent to dXY. The diagonal is the number of heterozygous sites divided by the total number of non-missing sites.

Simon

**Comment by mylena-s** [comment]
Thank you Simon! 

That was what I expected, but I was not completely sure from the code. 
Thanks for the clear answer again.


Cheers!
