### ISSUE TITLE
python/numpy version

### ISSUE THREAD

**Issue by AndreMonc** [simonhmartin/genomics_general#124]
Hi, 

Just wondering, what is the recommended python and numpy version for running these scripts? Thanks!

I just ran popgenWindows.py with python 3.12.5 and numpy 2.1.3 and got the following error:
`AttributeError: "np.NaN" was removed in the NumPy 2.0 release. Use "np.nan" instead.`

I then created an environment with python 3.9 and numpy 1.26.0 and the script seemed to run ok. This may help some future users.

Best,
Andre

**Comment by simonhmartin** [comment]
Hi Andre,
Thank you  - I recently became aware of this issue. The scripts are tested with numpy version 3.8, but I will try to update them to work with the latest numpy version asap.
Thanks,
Simon

**Comment by simonhmartin** [comment]
Hi, @tanpham15 , could you paste the error you got running freq.py? It doesn't contain any `np.NaN`s so I'm wondering if you got a slightly different error?

**Comment by tanpham15** [comment]
Hi Simon Martin,

Here is an error when I used numpy  v2.4.3

```
Traceback (most recent call last):
  File "/mnt/storage_2/scratch/pl0236-01/git_conda_env/genomics_general/freq.py", line 15, in <module>
    import genomics
  File "/mnt/storage_2/scratch/pl0236-01/git_conda_env/genomics_general/genomics.py", line 1707, in <module>
    class GenoWindow:
    ...<75 lines>...
            except: return np.NaN
  File "/mnt/storage_2/scratch/pl0236-01/git_conda_env/genomics_general/genomics.py", line 1739, in GenoWindow
    def addSite(self, GTs, position=np.NaN, ignorePosition=False):
                                    ^^^^^^
  File "/mnt/storage_2/scratch/pl0236-01/git_conda_env/numpy/lib/python3.14/site-packages/numpy/__init__.py", line 778, in __getattr__
    raise AttributeError(
    ...<3 lines>...
    )
AttributeError: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.
```

But when I installed numpy v1.26.4, it worked well
