### ISSUE TITLE
NA output of raxml_sliding_windows.py

### ISSUE THREAD

**Issue by tsm-tsm** [simonhmartin/genomics_general#125]
Hi Simon,
Recently I was following your instruction in general genomics pakage and running the tree for sliding wimdow with raxml. However my output file, .tree.gz file only showed 'NA' for each lines. I was wondering what may result to such a file.
Following is my command line:
`python  /home/ug1297/software1/genomics_general-master/VCF_processing/parseVCF.py -i out.recode.vcf  -o  out.geno.gz`
`python /home/ug1297/software1/genomics_general-master/phylo/raxml_sliding_windows-vi.py --windType sites -w 10000 --genoFile  out.geno.gz --prefix  out  --raxml raxmlHPC --model GTRGAMMAI --outgroup LSZJFL6 --threads 10 --log  raxml.log`
`less raxml.log`
started worker 0
started worker 1
started worker 2
started worker 3
started worker 4
started worker 5
started worker 6
started worker 7
started worker 8
started worker 9
2 windows queued |  1 results received |  1 results written.
4 windows queued |  3 results received |  3 results written.
6 windows queued |  5 results received |  5 results written.
8 windows queued |  7 results received |  7 results written.
10 windows queued |  9 results received |  9 results written.
......
Writing final results...

233 windows were analysed.

233 results were written.

Done.
`zcat out.trees.gz`
NA
NA
NA
NA

**Comment by tsm-tsm** [comment]
"When I add the --test parameter"
`less raxml.log`
outgroups: LSZJFL6
started worker 0
started worker 1
started worker 2
started worker 3
started worker 4
started worker 5
started worker 6
started worker 7
started worker 8
started worker 9
Sending window 0 to queue. Length: 10000
Window 0 received for analysis, length: 10000
raxml command:
raxmlHPC -s /home/ug1297/24-12-9/window-tree/LG01_31121_3171832_csclso.phy -n LG01_31121_3171832_csclso.phy -m GTRGAMMAI -o LSZJFL6 -V -f d -p 12345 --silent >>/dev/null
Sending window 1 to queue. Length: 10000
1 windows queued |  1 results received |  1 results written.
Window 1 received for analysis, length: 10000

**Comment by simonhmartin** [comment]
Hi, I recommend looking at the temporary files made when using the --test option. If these look normal, then I would guess it is an issue with your raxml installation. Perhaps the script is failing to call raxml.

I couldn't tell from your message whether the raxml.log file has anything in it? If not, that would also indicate that raxml is not running at all.

**Comment by tsm-tsm** [comment]
Thank you for your reply!
