### ISSUE TITLE
no attribute 'ploidy' while running genoToSeq.py

### ISSUE THREAD

**Issue by k-hench** [simonhmartin/genomics_general#13]
Hi Simon,

After updating to the current version of genomics_general I ran into an issue while running genoToSeq.py to generate a fasta file from genotypes.

I'm re-using some code that worked before, but now it produces an error:

```
$ python VCF_processing/parseVCF.py \
   -i simulated.phased.vcf.gz | \
   gzip > test.geno.gz

$ python genoToSeq.py \
     -g test.geno.gz \
     -s test.fa \
     -f fasta \
     --splitPhased

Traceback (most recent call last):
  File "genomics_general/genoToSeq.py", line 57, in <module>
    window = genomics.parseGenoFile(genoFile, names=samples, splitPhased=args.splitPhased)
  File "genomics_general/genomics.py", line 1683, in parseGenoFile
    reader=GenoFileReader(genoFile, splitPhased=splitPhased, ploidy=ploidy)
  File "genomics_general/genomics.py", line 1655, in __init__
    if splitPhased: self.names = makeHaploidNames(self.names, self.ploidy)
AttributeError: GenoFileReader instance has no attribute 'ploidy'

```
I traced back the issue and it seems to emerge when going from commit 

"54b0d75a79a6d4023bbc0e4cfc0c9719678bdde6" 

to 

 "d6758ea9742c0b649286bce4ebe645f8b2bbfa8c".

So, when using the old version I'm able to get my fasta.
The following runs fine:

```
git checkout 54b0d75a79a6d4023bbc0e4cfc0c9719678bdde6
python genoToSeq.py -g test.geno.gz -s test.fa -f fasta --splitPhased
```

Did I miss a change in the way that genoToSeq.py to be run, or is this a unintended side-effect of the update?

best regards,
Kosmas

**Comment by simonhmartin** [comment]
Hi Kosmas,
Sorry for the delay. This is a bug that I introduced with some recent updates to genomics.py. I think this should be fixed in the latest versions of genoToSeq.py and genomics.py.
-Simon

**Comment by k-hench** [comment]
Hi Simon,

Yes, thanks - the update fixed that bug indeed.
I guess this issue can be closed :)

best,
Kosmas
