### ISSUE TITLE
rawdatas

### ISSUE THREAD

**Issue by liufy11** [simonhmartin/genomics_general#19]
when I change my vcf file to geno,using the following command
python parseVCFs.py -t 25 -i mydata.vcf -o mydata.geno
the screen occurs many warnings like "Could not load .tbi/.csi index of mydata.vcf
WARNING empty window: mydata.vcf chrUnn_random 5300001-5400000"
At last the mydata.geno file is empty. Do you know what's wrong ? By the way ,Can you  add the sample datas  used in your scripts?

**Comment by simonhmartin** [comment]
Apologies for the delay. Did you figure this out? It looks like you need to index your VCF files with tabix.
