### ISSUE TITLE
No results written

### ISSUE THREAD

**Issue by BioGeorge** [simonhmartin/genomics_general#20]
Hi,

I‘ve been trying using popgenWindows.py to calculate the population statistics between pre-defined populations. All process works without error reports with the command:

`python2.7 ~/local/genomics_general/popgenWindows.py -w 50000 -m 5000 -f phased -g merged.test.geno -o output.csv.gz -T 4 -p pop1 -p pop2 --popsFile Poplist.txt --windCoords WinCoords.txt`

And I also used similar command to calculate more than two groups:

`python2.7 ~/local/genomics_general/popgenWindows.py -w 50000 -m 5000 -f phased -g merged.two.geno.gz -o output.csv.gz -p pop1 -p pop2 -p pop3 -p pop4-p pop5 -p pop6 -p pop7 -p pop8 --popsFile Poplist.txt --windCoords WinCoords.txt`

The geno file looks like this
![image](https://user-images.githubusercontent.com/42829875/64307829-d75bbb00-cfc9-11e9-93f7-88aa0ba7e60d.png)

But I got nothing except the header.
And the log told me like this:
> Writing final results...
>
> 187 windows queued, 187 results received, 0 results written.
> 187 windows were tested.
> 0 results were written.
> 
> Done.

I don't know why this happened. Could you help with this problem?

Thanks!

George.

**Comment by simonhmartin** [comment]
Hi George,
My guess is that your minimum sites per window (5000) is still too high. Try adding the option "--writeFailedWindows" and you should see the number of sites in each window.
BTW, if you are interested in pi and dxy, you will need to include invariant sites in your input file (the script does not assume that sites not present in the input are invariant, and it looks to me like you've only included SNPs).

**Comment by BioGeorge** [comment]
Many thanks for your reply. Indeed only snps was included in the input file. I've tried with all the sites and recalculated the statistics. The results look fine. Sorry for reply late.
