### ISSUE TITLE
error in popgenWindows.py

### ISSUE THREAD

**Issue by WANGyujian123** [simonhmartin/genomics_general#23]
Hi Simon,

I am having an issue with popgenWindows.py:
Traceback (most recent call last):
  File "/data/users/wangyujian/software/genomics_general_can_culculate_Dxy/popgenWindows.py", line 381, in <module>
    for window in windowGenerator:
  File "/data/users/wangyujian/software/genomics_general_can_culculate_Dxy/genomics.py", line 1867, in slidingCoordWindows
    site = reader.nextSite(asDict = extractSpecificGTs)
  File "/data/users/wangyujian/software/genomics_general_can_culculate_Dxy/genomics.py", line 1825, in nextSite
    self.precompDict, addToPrecomp=self.precompDict["__counter__"]<self.precompDict["__maxSize__"])
  File "/data/users/wangyujian/software/genomics_general_can_culculate_Dxy/genomics.py", line 1783, in parseGenoLine
    "position": int(lineData[posCol]) if posCol >= 0 else None,
ValueError: invalid literal for int() with base 10: 'filters'

My command line is as follows:
python /data/users/wangyujian/software/genomics_general_can_culculate_Dxy/popgenWindows.py -w 50000 -m 5000 -g /data/users/zhanglei/ossutil/shuju/damai-dp5-miss0.1-maf0.05.vcf -o output.csv.gz -f phased -T 10 -p popB B12,B16,B21,B25,B26,B34,B40,B44,B52,B59,B62,B63,B8 -p popC C13,C15,C24,C31,C34,C35,C3,C53,C5,C66,C9
Any insight would be appreciated. Thanks!

Yujian Wang

**Comment by simonhmartin** [comment]
Hi,
The problem seems to be related to the input file. I see the extension is .vcf. Did you convert to 'geno' format as described here: https://github.com/simonhmartin/genomics_general#processing-vcf-files

**Comment by WANGyujian123** [comment]
Oh,
thank you so much!



---Original---

**Comment by a601866950** [comment]
Hi Simon，

I have a similar problem as the author. I have converted my .vcf to 'geno' format but it still didn't work. The script I run did not write any ouput into the file.
Here is the output:
1061 windows queued, 1061 results received, 0 results written.
started worker 0
started worker 1
.......
2000 windows queued, 2001 results received, 0 results written.
1274 windows queued, 1274 results received, 0 results written.
3008 windows queued, 3008 results received, 0 results written.
3864 windows queued, 3864 results received, 0 results written.
4995 windows queued, 4995 results received, 0 results written.
......,
Writing final results...
96678 windows were tested.
0 results were written.
Done.

It seems all my result can not be written to the output. 
I have no idea with this error. The format of my 'geno' file is like this:

#CHROM  POS     B44     C13     B16     B59     C31     B62     B63     B12     C3      C35     B25     B8      B52     C66     C9      C53     C24     B26     C34     B34     C5      C15     B40     B21
1       43870   C/C     C/C     C/C     C/T     C/C     N/N     C/C     C/T     C/C     C/C     C/C     C/C     C/C     C/C     C/C     C/C     C/C     C/C     C/C     T/T     C/C     C/C     C/T     C/C
1       43895   A/A     A/A     A/A     A/T     A/A     N/N     A/A     A/T     A/A     A/A     A/A     A/A     A/A     A/A     A/A     A/A     N/N     A/A     A/A     A/T     A/A     A/A     A/T     A/A
1       43937   A/A     A/A     A/A     A/G     A/A     A/G     A/A     A/G     A/A     A/A     A/A     A/A     A/A     A/A     A/A     A/A     A/A     A/A     A/A     A/G     A/A     A/A     A/G     A/A

Any insight would be appreciated ! :  )

**Comment by simonhmartin** [comment]
Usually the problem with no output is that the minimum sites threshold (-m) is too high. Try decreasing that value. Also, add the option --writeFailedWindows to get some insights into how many sites are available in each window.

**Comment by a601866950** [comment]
Thanks! It really work.

**Comment by khf0008** [comment]
Hi Simon,
   I'm new to bioinformatics as a whole, so any help you can offer me with my error would be greatly appreciated!

This is what I run:

for x in {1..20} 'X'
do

        python $GENGEN/VCF_processing/parseVCF.py -i SAMN02922337_chr${x}.vcf.gz | gzip > SAMN02922337_chr${x}.geno.gz
        python $GENGEN/popgenWindows.py -w 50000 -m 10 -g SAMN02922337_chr${x}.geno.gz -o SAMN02922337_chr${x}_popgen_stats.csv.gz -f phased -p Red PM664.nemestrina -p Black PF660.nigra,PM592.tonkeana
done


This is the error I get:

started worker 0
Traceback (most recent call last):
  File "/opt/asn/apps/genomics_general_24may2019/genomics_general-master/popgenWindows.py", line 381, in <module>
    for window in windowGenerator:
  File "/mnt/beegfs/apps/dmc/apps/genomics_general_24may2019/genomics_general-master/genomics.py", line 1859, in slidingCoordWindows
    GTs = [site["GTs"][name] for name in names] if extractSpecificGTs else site["GTs"]
KeyError: 'PM592.tonkeana'

Thank you!

**Comment by simonhmartin** [comment]
Hi, The first thing to check is that the sample names in your input geno file match those in the command. The one it seems to have a problem with is PM592.tonkeana.

**Comment by khf0008** [comment]
Thank you! You're right- I see that the sample names in the input geno file do not match those in the command. In fact, the input geno file only has one sample. Do you know how I can make a new geno file that will have the correct sample names and number of samples? I've been trying to figure it out on my own with no luck.
