### ISSUE TITLE
genoToVCF Error

### ISSUE THREAD

**Issue by TD-lab-Wu** [simonhmartin/genomics_general#27]
Hi I am getting error fro geno to vcf conversion. I downloaded the .geno files  from https://reich.hms.harvard.edu/datasets

`**python genoToVCF.py -g panel7.geno -o panal17.vcf**`

```
Traceback (most recent call last):
  File "genoToVCF.py", line 61, in <module>
    genoFileReader = genomics.GenoFileReader(genoFile)
  File "/storage/artemis/com/shg29ny/geno_vcf/genomics.py", line 1805, in __init__
    if not headerLine: headerLine = getNext(genoFile)
  File "/storage/artemis/com/shg29ny/geno_vcf/genomics.py", line 1799, in getNext
    return generator.next() if sys.version_info.major < 3 else next(generator)
  File "/home/shg29ny/anaconda3/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9a in position 221: invalid start byte
```
Thank you for the support!

**Comment by simonhmartin** [comment]
Hi,
These geno files produced by the Reich lab are probably not compatible with my scripts. Do you know what the details of their file format is? Just viewing the first few lines of the file will show that.
The error you get is a file encoding error. It might occur if the input file is gzipped but the script doesn't know that because the file name doesn't end in .gz.

**Comment by TD-lab-Wu** [comment]
Thanks, I attached a sample data here. It was not gzipped file. Most of the data from David Reich Lab has the same format

[sample_data.zip](https://github.com/simonhmartin/genomics_general/files/4810596/sample_data.zip)

**Comment by simonhmartin** [comment]
Thanks. As I thought, this is a very different format and not compatible with my scripts. Perhaps somebody from the Reich lab could give you assistance in converting to VCF.
