### ISSUE TITLE
popsFile format for popgenWindows.py

### ISSUE THREAD

**Issue by mvdzee** [simonhmartin/genomics_general#3]
Hi there,

Any change you could provide an example of the format required for the popsFile in the popgenWindows.py script?
I have a simple .txt file with 2 columns and a header with Samples /t Population.

Thanks!

**Comment by simonhmartin** [comment]
Hi,
That format with first column as sample name and second column as
population name is correct. A header is not required, but I don't think
including a header will cause any problems.
-Simon
