### ISSUE TITLE
raxml_sliding_windows.py modification: raxmlHPC

### ISSUE THREAD

**Issue by markscherz** [simonhmartin/genomics_general#30]
Because the command for RAxML execution on my server (and by default) is `raxmlHPC` and not `raxml`, I had to modify raxml_sliding_windows.py to get it work on my server. This is a simple fix: replace all instances of 'raxml' with 'raxmlHPC' EXCEPT line 33, where the line must read
`treeFile = open("RAxML_bestTree." + localName, "r")`

Cheers,
Mark

**Comment by simonhmartin** [comment]
Hi Mark,
I think this could have been solved by just adding the flag `--raxml raxmlHPC` which would cause the script to then use that name for the executable. But your solution is fine too:)
Simon

**Comment by markscherz** [comment]
Hi Simon,
oh, that would have been much simpler. Interesting though; I used
--raxml /software/packages-15.1/RAxML/8.2.12-gnu-openmpi/bin/raxmlHPC to
get the function to work at all; I guess that might then have been
overkill, and I could have called it as you suggest instead and saved
myself quite a headache. Oh well!
Thanks for the rapid response!
Cheers,
Mark

*- - -Dr Mark D. Scherz, PhD (Dr rer. nat.)*
*PostDoctoral Researcher, Evolutionary Biology*
University of Konstanz

<mark.scherz@gmail.com>
Work Phone: +49 (0) 7531 88 4660
Skype: mark.scherz
@MarkScherz <http://www.twitter.com/@MarkScherz>
www.markscherz.com
www.squamatespod.com
