### ISSUE TITLE
ABBABABA error when running tutorial

### ISSUE THREAD

**Issue by stubbsrl** [simonhmartin/genomics_general#32]
When running both my data and the tutorial data with ABBABABAwindows.py I get the following error:

Traceback (most recent call last):
  File "genomics_general-master/ABBABABAwindows.py", line 223, in <module>
    if not args.addWindowID: outFile.write("scaffold,start,end,mid,sites,sitesUsed,ABBA,BABA,D,fd,fdM\n")
  File "/usr/lib/python3.6/gzip.py", line 260, in write
    data = memoryview(data)
TypeError: memoryview: a bytes-like object is required, not 'str'

I am using Python 3.6.9.

I am following the tutorial so this was the command:
python3 genomics_general-master/ABBABABAwindows.py \
-g data/hel92.DP8HET75MP9BIminVar2.chr18.geno.gz -f phased \
-o data/hel92.DP8HET75MP9BIminVar2.chr18.ABBABABA_mel_ros_chi_num.w25m250.csv.gz \
-P1 mel_mel -P2 mel_ros -P3 cyd_chi -O num \
--popsFile data/hel92.pop.txt -w 25000 -m 250 -T 2

Thanks,
Rebecca

**Comment by simonhmartin** [comment]
Hi Rebecca,
This bug should have been fixed in the version uploaded on 25 June (release v04 of genomics general). Can you try downloading the latest version and try again?

**Comment by stubbsrl** [comment]
Hello Simon,

Thanks so much for the quick answer. Yes, I downloaded the scripts originally on 24 June, so with the new (v04) the issue is solved. 

Thanks,
Rebecca
