### ISSUE TITLE
genomic statistics in sliding windows computation

### ISSUE THREAD

**Issue by alexisdiaz92** [simonhmartin/genomics_general#33]
Hi Simon,

I tried to calculate Fst and Dxy for one chromosome, but the output file did not give me the values requested. 
Is there something i am not considering? 

Here is the code I used: 

python popgenWindows.py -w 50000 -m 5000 -g CM020245.1.geno.gz -o CM020245.1.csv.gz -f phased -T 5 --popsFile pops.txt 

The populations as listed as: 

GRFL00	A1
GRFL01	A1
AMFL02	 B1
AMFL04  B2

Thanks in advance for your advice! 

<img width="385" alt="Screen Shot 2020-08-11 at 9 26 52 PM" src="https://user-images.githubusercontent.com/69564421/89971864-a5ab9500-dc19-11ea-836b-398bff9665e7.png">

**Comment by simonhmartin** [comment]
Hi,
Even though you have provided the popsFile, you still need to define the populations you want to use. Add `-p A1 -p A2 -p B1 -p B2`.
This will treat each individual as a separate population - is that what you want?

**Comment by simonhmartin** [comment]
You could also specify the whole set of populations on the command line without providing the popsFile, as follows:
`-p A1 GRFL00 -p A2 GRFL01 -p B1 AMFL02 -p B2 AMFL04`.

If you want to group multiple individuals into populations, that can also be done in the command like this:
`-p A GRFL00,GRFL01 -p B AMFL02,AMFL04`

**Comment by bioalexis92** [comment]
Thanks Simons for you answer, it was very helpful.
