### ISSUE TITLE
Error while processing geno file to frequency using freq.py

### ISSUE THREAD

**Issue by Akanksha-NBRI** [simonhmartin/genomics_general#36]
I used the parseVCF.py script to convert the VCF file into geno file without any error using command:
 python genomics_general-master/VCF_processing/parseVCF.py -i All_BIALLELIC_90mis_DP3.vcf.gz --skipIndels --minQual 30 --gtf flag=DP min=3 | bgzip -c > All_Biiallelic.geno.gz
When I  tried to run the freq.py script it gives me an error:
Starting 1 worker threads
Process Process-1:
Traceback (most recent call last):
  File "/home/genomics/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/genomics/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/media/genomics/2TB_WGS-NEW/ABBA-BABA/genomics_general-master/freq.py", line 42, in freqs_wrapper
    window = genomics.parseGenoFile(fileSlice, headerLine, names=sampleData.indNames)
  File "/media/genomics/2TB_WGS-NEW/ABBA-BABA/genomics_general-master/genomics.py", line 1842, in parseGenoFile
    GTs = [siteData["GTs"][name] for name in names] if extractSpecificGTs else siteData["GTs"]
KeyError: '79'
After which the script runs without any output.
The format of the file seems to be good with no obvious errors.
I am not sure what's happening. 
Kindly help.
Thanks
Akankshs

**Comment by simonhmartin** [comment]
Hi,
I'm not sure what the issue is.
Could you copy the header line of the .geno.gz file here?

**Comment by Akanksha-NBRI** [comment]
The geno file looks perfectly fine. I am attachig the header of the file
#CHROM	POS	88	108	139	159	265	350	351	403	
410	424	428	430	470	476	484	504	506	531	
544	546	628	630	680	681	685	687	728	742	
763	765	766	768	772	801	853	854	867	868	
870	915	932	991	992	997	1002	1006	1061	1062	
1063	1066	1070	1158	1166	1254	1257	1313	1317	1552	
1612	1622	1651	1652	1676	1684	1739	1741	1756	1757	
1793	1797	1819	1820	1829	1834	1835	1851	1852	1853	
1872	1890	1925	1942	1943	1954	2016	2017	2031	2053	
2057	2081	2091	2106	2108	2141	2159	2166	2171	2191	
2202	2212	2239	2240	2276	2278	2285	2286	2317	2370	
2412	4779	4807	4826	4840	4857	4884	4900	4939	4958	
5023	5104	5151	5165	5210	5236	5249	5253	5276	5279	
5349	5353	5395	5486	5577	5644	5651	5717	5718	5720	
5726	5741	5748	5757	5768	5772
For convenience I am also attaching a subset of the geno file with 10000 lines
[test.geno.gz](https://github.com/simonhmartin/genomics_general/files/5169397/test.geno.gz)
th

**Comment by Akanksha-NBRI** [comment]
I think I have figured out what the issue is. 
The names of  the individuals in the pop file and the geno file did not matched. The Key error shown **KeyError: '79'** represents the name of the individual that was not matching. It was 79_2 in the geno file which coded as 79 in the pops file. This is what caused the issue.
I think this may help someone else if they run into same issue.
Thanks. :-)

**Comment by simonhmartin** [comment]
Ok that explains it.
