### ISSUE TITLE
fasta option for variant only vcfs

### ISSUE THREAD

**Issue by stsmall** [simonhmartin/genomics_general#4]
Hi @simonhmartin,
Thank you for making a very useful set of tools for popgen. 
For my species the --emit_all_confident_sites creates a very large file. Thus I call variants with HaplotyeCaller (only outputting the variant positions), filter the individual vcfs, union for population variable sites, and then recall missing sites using freebayes with population information.
I think this causes an issue for me with your set of scripts since some of the window slicing relies on invariant sites which the README on twisst indicates you leave in your vcfs. Or am I mistaken? 
Would it be possible to add a option to take a fasta file, the same used when snp calling, to fill the invariant sites when calling phyml_sliding_windows.py?
thank you,
@stsmall

**Comment by simonhmartin** [comment]
Hi @stsmall,
Apologies for the long delay - I haven't been receiving notifications of questions for a long time!
I don't think having no invariant sites will be a problem. The windows can be defined by genome coordinates or by number of sites.
