### ISSUE TITLE
only getting pi_all in popgenWindows.py output

### ISSUE THREAD

**Issue by aherbotany** [simonhmartin/genomics_general#43]
Hi Simon,
I am a new user implementing your popgenWindows.py to obtain Fst and Dxy calculations across 6 populations from RAD-Seq data, but my output only contains pi_all calculation. I have tried various -w and -m values, but that still does not give me fst or dxy columns.

Here's an example of what I've run: 
python popgenWindows.py -w 20000 -g vcf.geno.gz -o csv.gz -f phased -T 10 --writeFailedWindow -s 2500 -m 1 --popsFile geopopname.txt

Here is an example output:
scaffold,start,end,mid,sites,pi_all
scf7180000845757,1,20000,8258,1,0.106
scf7180000787816,1,20000,7592,1,0.1035
scf7180000975282,1,20000,9347,1,0.2884
scf7180001008466,1,20000,987,3,0.152
scf7180000807401,1,20000,7048,6,0.1228
scf7180000777439,1,20000,10585,1,0.1018

Any idea why I might not be getting Fst and Dxy in the output? 
I'm also wondering why I am only getting pi_all rather than pi for each of the six populations. 

Thanks,
Adriana

**Comment by aherbotany** [comment]
I should also note that I'm getting these warnings before it starts the counts and writes results:

/opt/miniconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3335: RuntimeWarning: Mean of empty slice. out=out, **kwargs) 
/opt/miniconda3/lib/python3.7/site-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars ret = ret.dtype.type(ret / rcount)

**Comment by simonhmartin** [comment]
Hi,
To get individual population outputs, you also need to name them in the command line, like `-p pop1 -p pop2`
And the population names obviously need to match names present in the second column of the popsFile.

The warning you're getting is not a major concern, it happens if the script encounters a window with no genotype data.
