### ISSUE TITLE
2 minor phylo bugs (with fixes?)

### ISSUE THREAD

**Issue by tjthurman** [simonhmartin/genomics_general#47]
Hi Simon,

Thanks for the great tool! I've been using genomics general to run some windowed phylogenetic trees with phyml and raxml, and I ran in to a couple small (but seemingly easy to fix) bugs.

**For phyml_sliding_windows.py**:

I was using pre-defined windows and kept getting this error message:
```
Traceback (most recent call last):
  File "/home/tt164677e/bin/genomics_general/phyml_sliding_windows.py", line 408, in <module>
    for window in windowGenerator:
  File "/home/tt164677e/bin/genomics_general/genomics.py", line 2031, in predefinedCoordWindows
    reader=GenoFileReader(genoFile, headerLine, splitPhased=splitPhased, ploidy=ploidy)
  File "/home/tt164677e/bin/genomics_general/genomics.py", line 1835, in __init__
    self.names = headerLine.split()[firstSampleCol:]
AttributeError: 'list' object has no attribute 'split'
```

I think the problem is in line 406 of phyml_sliding_windows.py, with the positional arguments of `genomics.predefinedCoordWindows` not matching up to the positions as they're defined in genomics.py. Changing line 406 to use the argument name for indNames fixed it, e.g.:

```
windowGenerator = genomics.predefinedCoordWindows(genoFile, windCoords, names = indNames)
```

**For raxml_sliding_windows.py**:

At first I couldn't even run `python raxml_sliding_windows.py -h`, which would give me this error:

```
  File "/home/tt164677e/bin/genomics_general/phylo/raxml_sliding_windows.py", line 329
    print "\nDone."
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("\nDone.")?
```

Changing line 329 to the error message's suggestion of `print("\nDone.")` did the trick. 

If it matters, I'm using Python v3.8.3. I forgot to write down what day I download genomics general, but looks like I'm probably on commit ff736c5.

Thanks,
Tim

**Comment by simonhmartin** [comment]
Hi Tim,
You're right. This was a recent addition to `genomics.predefinedCoordWindows` and I anticipated some unexpected bugs like this. Your fix makes sense and I will incorporate it.
The second one is a python version error. I haven't yet updated the raxml script to run with python 3. Will get to that eventually.
Thanks,
Simon

**Comment by nbedelman** [comment]
Hey Simon, 
I had the same issue but using sliding sites, and the same fix works :) Same for sliding coordinates.
Best
Nate
