### ISSUE TITLE
Testing introgression of individuals

### ISSUE THREAD

**Issue by zhen-fu** [simonhmartin/genomics_general#48]
Hi there, 
    Have been really enjoying your code and have been reading your papers. I got a quick questions here about using ABBABABAwindows.py in genomics_general to test whether there are certain windows exhibit evidence of introgression at the individual level. 
For ABBABABAwindows.py (in the example of the manual page):

python ABBABABAwindows.py -g /zoo/disk1/shm45/vcf/set62/set62.chr21.DP5GQ30.AN100MAC1.diplo.gz -f phased -o output.csv -w 100000 -m 100 -s 100000 -P1 A -P2 B -P3 C -O D -T 10 --minData 0.5 --popsFile pops.txt --writeFailedWindows --polarize &

Could A, B, C, and D be an individual instead of a population? Thank you!

**Comment by simonhmartin** [comment]
Hi, sorry for the long delay!
It's OK to use single individuals for each population, but of course the data will be less reliable than if you use multiple individuals.
