### ISSUE TITLE
Phyml bootstrapping

### ISSUE THREAD

**Issue by npb596** [simonhmartin/genomics_general#56]
Hello,

I have used the following command for testing a single gene alignment:

    ~/genomics_general/phylo/phyml_sliding_windows.py -T 1 -g ~/arctoides_project/samples/Macaque_merged.filtered.geno -p tree_files/UQCRH -w 11573 -M 1 --windType predefined --windCoords temp_coordinates.bed --bootstrap 10 --model HKY85

and the program outputs UQCRH.data.tsv and UQCRH.trees.gz file, then 10 BS.trees.gz files. Although this seems to be working as intended the bootstrap files are generated after the initial tree, whereas I would have assumed a most likely tree would be generated after the bootstrapping. This certainly seems to be the case when I've used the phyml command-line application. So I am essentially wondering if I am missing some option or if I am simply misunderstanding how the boostrapping is implemented in the script.

**Comment by simonhmartin** [comment]
Hi, yes these bootstrap trees are not used for inference, they are just re-inferred from resampled alignments. The best tree returned is the same whether you add bootstrapping or not. Hence, this is more a way to explore the confidence in the best tree.

**Comment by yzliu01** [comment]
Hi, Simon, many thanks.

I am just trying with your advice.
I. execution without `--bootstraps` see below. It's running. It runs in 10 windows as well even I did not specify `--test`. There are *.data.tsv, *.trees.gz, phyml_tmpt53Jp8, and no bootstrap files. Is it proper? I'll update the results when it ends.
```
python ~/phyml_sliding_windows.py --threads 10 --genoFile $GENO --prefix ./bal_bootstraps_exclude /ctg1_2_3.NJ -w 50 --windType sites --optimise n --model GTR --tmp ./bal_bootstraps_exclude

10 windows queued | 0 results received | 0 results written.
10 windows queued | 0 results received | 0 results written.
```
II. Execution using `--test `and `--log xxxx`, still running as well, and the message in the log file as below.
```
. The file name'/..../merge_vcf_per_contig_new2/bal_no_bt/phyml_tmpUaVKaW/contig_003_1152_35968_0hC3ru.phy' is **too long**.
. Type any key to exit.
```
Does this matter?

**Comment by simonhmartin** [comment]
So phyml is saying your file name is too long. So have you tried shortening the prefix?

**Comment by yzliu01** [comment]
Hi, I shortened the path name to the .geno file. It seem to be working better. In the log file, I see different number of patterns found ....
for example, `50, 38... patterns found (out of a total of 50 sites)`
### below is part of text from the logfile
```
. Command line: phyml --input /XXXXXXXXX/bal_no_bt_new2/phyml_tmpVaIHKH/contig_003_1152_35968_MUIg5f.phy --model GTR -o n -b 0 
  ////////////////////////////////////.\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
  \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\.//////////////////////////////////////////

        . Sequence filename:				 contig_003_1152_35968_MUIg5f.phy
        . Data type:					 dna
        . Alphabet size:				 4
        . Sequence format:				 interleaved
        . Number of data sets:				 1
        . Nb of bootstrapped data sets:			 0
        . Model name:					 GTR
        . Proportion of invariable sites:		 0.000000
        . Number of subst. rate catgs:			 4
        . Gamma distribution parameter:			 1.000000
        . 'Middle' of each rate class:			 mean
        . Nucleotide equilibrium frequencies:		 empirical
        . Optimise tree topology:			 no
        . Evaluated tree:				 "BioNJ"
        . Optimise branch lengths:			 no
        . Optimise substitution model parameters:	 no
        . Run ID:					 none
        . Random seed:					 1656683062
        . Subtree patterns aliasing:			 no
        . Version:					 3.3.20190321
        . Byte alignment:				 32
        . AVX enabled:					 yes
        . SSE enabled:					 yes

  ////////////////////////////////////.\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
  \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\.//////////////////////////////////////////

. 50 patterns found (out of a total of 50 sites). 

. 0 sites without polymorphism (0.00%).


. Computing pairwise distances...

. Command line: phyml --input /XXXXXXXXX/bal_no_bt_new2/phyml_tmpVaIHKH/contig_003_1152_35968_MUIg5f.phy --model GTR -o n -b 0 

  ////////////////////////////////////.\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
  \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\.//////////////////////////////////////////

        . Sequence filename:				 contig_003_36320_46780_OwtUKm.phy
        . Data type:					 dna
        . Alphabet size:				 4
        . Sequence format:				 interleaved
        . Number of data sets:				 1
        . Nb of bootstrapped data sets:			 0
        . Model name:					 GTR
        . Proportion of invariable sites:		 0.000000
        . Number of subst. rate catgs:			 4
        . Gamma distribution parameter:			 1.000000
        . 'Middle' of each rate class:			 mean
        . Nucleotide equilibrium frequencies:		 empirical
        . Optimise tree topology:			 no
        . Evaluated tree:				 "BioNJ"
        . Optimise branch lengths:			 no
        . Optimise substitution model parameters:	 no
        . Run ID:					 none
        . Random seed:					 1656683062
        . Subtree patterns aliasing:			 no
        . Version:					 3.3.20190321
        . Byte alignment:				 32
        . AVX enabled:					 yes
        . SSE enabled:					 yes

  ////////////////////////////////////.\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
  \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\.//////////////////////////////////////////



. 45 patterns found (out of a total of 50 sites). 

. 0 sites without polymorphism (0.00%).


. Computing pairwise distances...

. Command line: phyml --input /XXXXXXXXX/bal_no_bt_new2/phyml_tmpVaIHKH/contig_003_1152_35968_MUIg5f.phy --model GTR -o n -b 0 
```

**Comment by yzliu01** [comment]
hi, yes, you understood me correctly. Idealy using whole genome, it's also fine to use a part of genome just for estimating the reliability of species. Since your another script that considers ploidy to calculate distance matrix using vcf as an input, I thought this script conveniently uses the .dist file to generate trees with bootstrap values running for each window, and then I can probably make a consensus tree based these trees. So I just simply thought the` --bootstraps` does the usual bootstrapping when building a tree. Now it's clear to me with your details. Yes, phyml is the alternative option that I'll try.
Many thanks.

**Comment by simonhmartin** [comment]
Ok, good luck. If you can convert your data into an alignment format like fasta or phylip, you should be able to run all phylogenetic software on the whole alignment, with bootstrapping etc.
