### ISSUE TITLE
extractCDSAlignments KeyError

### ISSUE THREAD

**Issue by stsmall** [simonhmartin/genomics_general#6]
Hi @simonhmartin ,
I really like the idea of this script, it works well with the modules in genomics.py. However, I seem to be running into some problems when running it. I have a gff file and a geno file that I created a tabix index using tabix -p vcf -h FOO.geno.gz. When I run the command:

python genomics_general/extractCDSAlignments.py --gff test.gff -g FOO.geno.gz -s sample1.1 sample1.2
It returns a KeyError:
Extracting 2 gene sequences from X
AFUN000184-RA.mrna1
Getting region X:913961-917834 from geno file...
Traceback (most recent call last):
  File "genomics_general/extractCDSAlignments.py", line 46, in <module>
    window = genomics.parseGenoFile(genoStream.stdout, names=args.samples, includePositions=True, splitPhased = args.split, headerLine=headerLine)
  File "genomics_general/genomics.py", line 1592, in parseGenoFile
    names = [n + "_" + letter for n in names for letter in string.ascii_uppercase[:ploidyDict[n]]]
KeyError: 'sample.1.1'

If I leave out the sample names it defaults to printing 4 haplotypes but it names the output as N|N or G|G, basically from the nucleotide names.

Any suggestions?
thank you,
@stsmall

**Comment by stsmall** [comment]
Hi @simonhmartin,
The issue was in the parseGenoFile function in genomics.py. Line 1584 you pull the header from the geno file, but the extractCDSAlignments  passes a tabix output. The headerLine options is not used in the parseGenoFile function. I changed the code to simply check for the headerLine before a readline() on the geno file.

The second issue was in the extractCDSAlignments.py where the function makeAlnString is called with "format" instead of "outFormat". I just changed the text from "format" to "outFormat".

After those alterations it seems to run now without error. The "--no-split" option is not working but I dont need it atm.
thanks,
@stsmall

**Comment by gmkov** [comment]
Hi @stsmall , thanks for sharing your issue/solution! Could you please show me your code change in the parseGenoFile function to check for headerLine? I think I'm running into the same issue but not sure how to tackle it. Thank you

**Comment by stsmall** [comment]
Hi @gmkov,
In the newest version, I replaced line 1769 to read:
    #get file headers                                                                                                                                                                                               
    if headerLine:
        headers = headerLine.split()
    else:
        headers = genoFile.readline().split()
    allNames = headers[2:]

hope that helps!
