### ISSUE TITLE
ABBABABAwindows.py and popgenWindows.py  KeyError

### ISSUE THREAD

**Issue by Angel-Popa** [simonhmartin/genomics_general#60]
Hi Simon, 

I am trying to use ABBABABAwindows.py, and I keep getting this error. I have checked that my individuals and populations have the same name in the geno file as in the population file. 

```
Traceback (most recent call last):
  File "./code/simonmartin_scripts/ABBABABAwindows.py", line 320, in <module>
    for window in windowGenerator:
  File "/work/Angel/Projects/inProgress/Neo_pop_gen/code/simonmartin_scripts/genomics.py", line 2087, in predefinedCoordWindows
    GTs = [site["GTs"][name] for name in names] if extractSpecificGTs else site["GTs"]
  File "/work/Angel/Projects/inProgress/Neo_pop_gen/code/simonmartin_scripts/genomics.py", line 2087, in <listcomp>
    GTs = [site["GTs"][name] for name in names] if extractSpecificGTs else site["GTs"]
KeyError: 'aquilonis_Broome_Male_2015_1'
```

As a side note, I also get this error when I run popgenWindows.py if my geno file only includes two populations.

**Comment by simonhmartin** [comment]
Hi Angel,
Itseems to have failed to find the sample "aquilonis_Broome_Male_2015_1" in the .geno file. The first thing to check is that there is a header line in your .geno file and that the individual names match those supplied exactly.
Hopefully that solves it.
Simon

**Comment by Angel-Popa** [comment]
Hi Simon, 

Thanks for the quick reply! It is indeed a problem with my data; parsevcf.py removed those individuals from the .geno file. I cannot run the scripts. 

Thank you for the fantastic scripts. I would close this now.
