### ISSUE TITLE
error while using phyml_sliding_windows.py "No module named 'genomics'

### ISSUE THREAD

**Issue by Jungal10** [simonhmartin/genomics_general#63]
I was able to use all the other tools to come from bams to trees. although when I reach the step to use phyml, it always fails with a missing module:

```
phyml_sliding_windows.py", line 19, in <module>
    import genomics
ModuleNotFoundError: No module named 'genomics'
```

I have phyml installed, I tried with the environment where the ETE toolkit is installed as well and I always go back to this missing module. 

Any help to solve the issue?

Thanks

P.S. I tried the same with Raxml and I had the same problem (I have raxml installed as well)

**Comment by simonhmartin** [comment]
Hi, you need to make sure you have the genomics.py script in the same directory or in your PYTHONPATH variable.

**Comment by Jungal10** [comment]
Oh well, that solved it. Glad it was such a simple thing. Thank you for the extremely fast answer!
