### ISSUE TITLE
sliding_windows.py error

### ISSUE THREAD

**Issue by Jungal10** [simonhmartin/genomics_general#67]
I am tryin got prepare a file for using with twist. 

With the following command: 

`python /projects/jgoncal1/tools/bin/genomics_general/phylo/phyml_sliding_windows.py -T 10 -g <VCF_FILE>  --prefix <prefix_name> -w 50  --minPerInd 1   --windType  sites --model GTR --optimise n
`

I always end up with: 

```
Traceback (most recent call last):
  File "/projects/jgoncal1/tools/bin/genomics_general/phylo/phyml_sliding_windows.py", line 408, in <module>
    for window in windowGenerator:
  File "/projects/jgoncal1/tools/bin/genomics_general/genomics.py", line 1986, in slidingSitesWindows
    site = reader.nextSite(asDict = extractSpecificGTs)
  File "/projects/jgoncal1/tools/bin/genomics_general/genomics.py", line 1881, in nextSite
    return parseGenoLine(line, self.names, self.scafCol, self.posCol, self.firstSampleCol, self.type, self.splitPhased, asDict,
  File "/projects/jgoncal1/tools/bin/genomics_general/genomics.py", line 1840, in parseGenoLine
    "position": int(lineData[posCol]) if posCol >= 0 else None,
ValueError: invalid literal for int() with base 10: 'filters'
```

I tried multiple VCF files, phased, not phased, smaller, bigger, different windows sizes. I have always the same issue. I have the PYTHONPATH exported to the genomis_general folder, everything. I do not know what might be causing it.
Thank you

**Comment by Jungal10** [comment]
Got the mistake. I was using the VCF as input instead of the geno file.  It serves as help for the future distracted users

**Comment by Callithrix-omics** [comment]
thank you for this post just saved me gobs of time trying to figure out a dumb (on my part) mistake!

**Comment by Jungal10** [comment]
> thank you for this post just saved me gobs of time trying to figure out a dumb (on my part) mistake!

We have all been there. Glad it helped!
