### ISSUE TITLE
NA output of raxml_sliding_windows.py 

### ISSUE THREAD

**Issue by caiyc1994** [simonhmartin/genomics_general#7]
Hi Simon,
Recently I was following your instruction in general genomics pakage and running the tree for sliding wimdow with raxml. However my output file, .tree.gz file only showed 'NA' for each lines. I was wondering what may result to such a file.
Following is my command line:
 python2.7 /home/caiyc/software/genomics_general/phylo/raxml_sliding_windows.py -g Bi_SNP_9_pop_DF_miss_polar_paralog_Density.geno -f phased --windType coordinate -w 50000 -M 500 -S 50000 -p slidingTREE/phased --individuals FC-01,HC-02,HM-01,HN-02,PC-01,PN01,ZG_M1 --outgroup M_kudoi --raxml /home/caiyc/software/RAxML_8.2.8/raxmlHPC --model GTR -T 4 

Thanks!
caiyc

**Comment by simonhmartin** [comment]
Hi caiyc,
This usually happens because the number of genotyped sites available per window is lower than the minimum specified (500 in your case). Is that possible?
-Simon

**Comment by caiyc1994** [comment]
Hi Simon,
Thanks for your quick replying.
Here is my .tsv result file, 
scaffold        start   end     mid     sites
Contig0 1       100000  nan     0
Contig0 100001  200000  182108  548
Contig0 200001  300000  212973  429
Contig0 300001  400000  359102  1721
Contig0 400001  500000  447995  2171
Contig0 500001  600000  553264  2000
Contig0 600001  700000  641238  1565
Contig0 700001  800000  744583  1149
Contig0 800001  900000  848283  1004
Contig0 900001  1000000 959149  1304
Contig0 1000001 1100000 1047684 1381
Contig0 1100001 1200000 1153469 1548
Contig0 1200001 1300000 1245010 1345
Contig0 1300001 1400000 1358299 1240
Contig0 1400001 1500000 1430776 491
Contig0 1500001 1600000 1513647 4
Contig0 1600001 1700000 1639053 10
Contig0 1700001 1800000 nan     0
Contig0 1800001 1900000 1881738 461
Contig0 1900001 2000000 1923116 990
Contig0 2000001 2100000 2081643 316
Contig0 2100001 2200000 2128298 490
Contig0 2200001 2300000 2217771 44
Contig0 2300001 2400000 2379299 587
Contig0 2400001 2500000 2458089 1475
Contig0 2500001 2600000 2555964 2066
Contig0 2600001 2700000 2653951 2534
___________________________________________________________________________________________________________
And I think if some windows had less than 500 genotyped sites, there are some windows that pass such a criteria while in the .tree file, waht I see was 'NA' for all the windows.
______________________________________________________________________________________________________
caiyc@ubuntu:~$ grep 'NA' phased.trees | wc -l
2726
caiyc@ubuntu:~$ wc -l phased.trees 
2726 phased.trees
_______________________________________________________________________________________________________
 That is what exactly confused me, because all the windows were wrote as NA. and following is the processing information:
199 windows queued |  199 results received |  199 results written.
437 windows queued |  437 results received |  437 results written.
671 windows queued |  671 results received |  671 results written.
874 windows queued |  874 results received |  874 results written.
1109 windows queued |  1109 results received |  1109 results written.
1396 windows queued |  1396 results received |  1396 results written.
1641 windows queued |  1641 results received |  1641 results written.
1873 windows queued |  1873 results received |  1873 results written.
2146 windows queued |  2146 results received |  2146 results written.
2473 windows queued |  2473 results received |  2473 results written.
_________________________________________________________________________________________________________
Again, thanks for your kind help.
caiyc

**Comment by simonhmartin** [comment]
Okay, this is not a simple issue. For now I would recommend trying my other script phyml_sliding_windows.py. If that fails too, it will indicate that there is an issue with the input data. If that works, then it is probably a RAxML issue.

**Comment by cbrock2** [comment]
Hi all,

Incidentally, I have had a similar issue recently. The phyml script works fine for the same data, but the raxml does not (though it did previously). I've tried replacing 'raxml' in the script command with the path with no luck. I can use the --raxml path flag with a non-existent path and it doesn't give an error, but creates NA output, so its seems as if this is being ignored.

Since this worked a few weeks ago on our cluster, I assume the issue is raxml. However, I checked the path and it's good. Any other ideas as to what I should look at? 

Thanks a lot for your time and your great scripts.

Best,

Chad

**Comment by simonhmartin** [comment]
Hi Chad,
It is likely this is a compatibility issue with the version of RAxML. I haven't tested or updated the script in a year, so it could easily be the case that something has changed in a recent version of RAxML. Can you let me know what version of RAxML you have installed so I can look into this?
Cheers,
Simon

**Comment by cbrock2** [comment]
Hi Simon,

The current version installed is 8.2.12 (raxmlHPC-PTHREADS-AVX command, I believe this is the latest version from this past August). We did just switch clusters, with all new module installation. However, I have been trying other versions locally on my mac with no luck either. I had issues with a previous raxml version that needed -T for threads and didn't recognize --silent, but editing the python script solved this. This hasn't worked thus far for any raxml version I've tried, and many don't have any issues with these commands. Do you have a version that should most certainly work? I can install and try that to see if there is something else I'm missing. I've tried running with --test and --verbose but the raxmlCommand isn't printed, so it seems that I'm not even getting that far. 

This worked ~1 month ago on the same data, and I've been scratching my head trying to figure out where I'm now going wrong. The phyml script works, but I can't seem to replicate what I did previously with raxml. I'll keep digging and try to ID where the issue may lie. If you have any suggestions where I should look, please let me know if you have a chance. 

Thanks again for the help and the incredibly useful scripts. It's greatly appreciated.

Best,

Chad

**Comment by simonhmartin** [comment]
Hi Chad,
I've just uploaded a new version of the raxml script. The script is working for me, both with RAxML version 8.2.9 and 8.2.12. 
I'm actually not sure what (if anything) I have changed made the script work (I didn't test it before making a few changes).
Most changes are just improvements to the handling of temporary files, which I've intended to do for ages, but one significant one is there is no longer a need to specify the --genoFormat argument.
If this version still fails for you, then it must be something else and we'll have to look more closely.

Just FYI, the most common cause of problems with these scripts is that users don't realise that by default the script expects zero missing sites when making 'coordinate' windows, so if you have incomplete data you have to specify the minimum number of sites per window (-M). But presumably that's not your issue if the phyml script is working for you.

**Comment by cbrock2** [comment]
Hi Simon,

It works good now. I did not realize the minimum site flag, and I think this was the problem as I had recently switched from site to coordinate. Thanks for the clarification and thank you for the updated script (and for all the helpful scripts).

Best,

Chad
