### ISSUE TITLE
popFreq analysis run indefinitely

### ISSUE THREAD

**Issue by germmtz** [simonhmartin/genomics_general#71]
Hi Simon,

Thank you for the time and efforts put in the development of these popgen scripts !  
I have an issue when running the "popgenWindows.py " script with the "popFreq" analysis (I want to compute Tajima's D).

Here is my command:

python3 ./bin/genomics_general/popgenWindows.py --windType predefined --windCoords ./data/WindCoord.bed --minSites 500 -g ./results/1001genomes_snp_chr1.geno.gz -o ./results/1001genomes_snp_chr1_south_sweden_stats_Dtaj_20k_5k.csv -f phased --ploidyFile ./data/ploidy.txt -T 8 -p south_sweden --popsFile ./data/adm_pop.txt --analysis popFreq

Then, the program runs indefinitely and I have no outputs.  Here is the error file: 

Starting 8 worker threads
Process Process-3:
Traceback (most recent call last):
  File "/work/FAC/FBM/DEE/lkeller/default/gmontaze/Arabido/bin/.conda/envs/truc/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/work/FAC/FBM/DEE/lkeller/default/gmontaze/Arabido/bin/.conda/envs/truc/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/work/FAC/FBM/DEE/lkeller/default/gmontaze/Arabido/bin/genomics_general/popgenWindows.py", line 49, in stats_wrapper
    statsDict.update(Aln.groupFreqStats())
  File "/work/FAC/FBM/DEE/lkeller/default/gmontaze/Arabido/bin/genomics_general/genomics.py", line 999, in groupFreqStats
    siteBaseCounts = np.apply_along_axis(binBaseFreqs,0,self.numArray[np.ix_(seqIdx,siteIdx)],asCounts=True)
  File "<__array_function__ internals>", line 5, in apply_along_axis
  File "/work/FAC/FBM/DEE/lkeller/default/gmontaze/Arabido/bin/.conda/envs/truc/lib/python3.8/site-packages/numpy/lib/shape_base.py", line 402, in apply_along_axis
    buff[ind] = asanyarray(func1d(inarr_view[ind], *args, **kwargs))
  File "/work/FAC/FBM/DEE/lkeller/default/gmontaze/Arabido/bin/genomics_general/genomics.py", line 598, in binBaseFreqs
    if asCounts: return np.bincount(numArr, minlength=4)
  File "<__array_function__ internals>", line 5, in bincount
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 2.63 TiB for an array with shape (360777252943,) and data type int64

I think the problem might be related to some specifics in the data,  because this code works perfectly when applied to other chromosomes/windows on the same population, or on the same set of windows for other populations. There are here 156 individuals, and ~ 200 windows of 20 kb with 5 kb overlap.

If you have any clue on this, it would be very helpful !
Thank you very much,

Germain

**Comment by simonhmartin** [comment]
Hi Germain,
I don't know what the specific cause is, but I recall that similar errors have been seen before by users who have either multi-base genotypes like `A/TT` or asterisk like `*/*`. These will not be recognised and could cause problems. Could this be the issue in your case?
Simon

**Comment by germmtz** [comment]
Hi Simon,
Thank you for the quick reply.
I think there are no such genotypes in my vcf. After a quick check, the unique set of values for the genotypes ("GT" field) across all individuals are:
 "0|0" "./." "1|1" "2|2" "1/1" "3|3" "3/3" "4|4" "2/2" "7|7" "5|5" "6|6"
Germain

**Comment by simonhmartin** [comment]
Hi Germain, hoe about in the .geno.gz file?

**Comment by germmtz** [comment]
Hi Simon, 

There are indeed multi-base genotypes in the .geno.gz, such as `AAC|AAC` or `AAATG|AAATG` (not sure to understand what they mean though ?)

However, I also checked other populations for which I do not have this issue, and I also found such multi-base genotypes there as well, suggesting that they might not be the (only?) origin of the problem.

Thank you again for your help,

Germain

**Comment by simonhmartin** [comment]
Hmm, ok well the first thing is definitely remove them. Depending on the genotyper you have used, they might represent indels (i.e. where the reference is someing like `A` and the alternate allele is `AAC` you can see this in the vcf. If so, just remove them either by searching for any lines with genotypes that are more than 3 characters long, or by specifying in the genotyper not to output indels. However, if you have used something like Freebayes for genotyping, you can have haplotypes in the VCF in which both the reference and alternate alleles represent multiple sites in a single line of the VCF. I have options to deal with this in the parseVCF script, so let me know if you'll be needing those.

**Comment by simonhmartin** [comment]
No problem. Good to hear that it's working now.
