### ISSUE TITLE
ABBABABAwindows.py error

### ISSUE THREAD

**Issue by rturba** [simonhmartin/genomics_general#80]
Hello!

I'm trying to run the `ABBABABAwindows.py` script using python3. I was able to run `popgenWindows.py` on my files with no problems, but now even trying to get the manual from the `ABBABABAwindows.py` using the `-h` command, I get the following error:

```
python ABBABABAwindows.py -h
File "/u/scratch/r/rturba/stickleback/genomics_general-master/ABBABABAwindows.py", line 85
    def writer(writeQueue, out, writeFailedWindows=False, verbose):
                                                                                                        ^
SyntaxError: non-default argument follows default argument
```
Any ideas what might be going on? :(

**Comment by ChanyeeNicole** [comment]
hello, rturba. I also meet the same erro and I solve it in following commands, 
vim /u/scratch/r/rturba/stickleback/genomics_general-master/ABBABABAwindows.py +85
then u should access edit mode of vim
and change  "def writer(writeQueue, out, writeFailedWindows=False, verbose)"  to  "def writer(writeQueue, out, verbose, writeFailedWindows=False)"

**Comment by simonhmartin** [comment]
Hi rturba, this looks like an error I introduced on the last push. ChanyeeNicole's fix will remove the error, but it's actually not correct because the arguments can't be swapped. Instead use
`writer(writeQueue, out, writeFailedWindows=False, verbose=False)`
I'll fix this on my next push.
Simon

**Comment by rturba** [comment]
Yay! It worked :D Thank you both so much for being so quick in helping me out!
