### ISSUE TITLE
something goes wrong when used "raxml_sliding_windows.py"

### ISSUE THREAD

**Issue by zhangqiong151** [simonhmartin/genomics_general#84]
Hi sir,
sorry to bother you, when I used "raxml_sliding_windows.py" with the command "python raxml_sliding_windows.py --windType coordinate -M 50 -Mi 200 -p snp  --log ./log -w 50000 -g vcf_file --raxml ./py2/bin/raxmlHPC", the errors occur, just like:
 
Problem reading alignment file
ERROR: Bad base (*) at site 1063 of sequence 5
Printing error context:

CNCGCCCTGTGACCCGGCG***GCCCGTCGGGTAGGCACC    

however, before to construct the tree, I have replace "*" with "N" in the vcf_file.  Could you please give me some advice?

**Comment by simonhmartin** [comment]
This should not be happening if you really have replaced all "*" with "N" in the vcf. If you are sure you have done this, could you post a subset of your input file so I can try to reproduce the error?

**Comment by zhangqiong151** [comment]
Thank you for your reply, I'll try again, if  it is not successful, I'll send you the vcf file.Thank you.
