### ISSUE TITLE
Some bugs in popgenWindows.py

### ISSUE THREAD

**Issue by wushyer** [simonhmartin/genomics_general#95]
Hi Simon,

    I am running the popgenWindows.py on a haploid genome based vcf geno files with below command:
python popgenWindows.py -w 20000 -g input.geno.gz -o output.csv.gz --ploidy 1 -f haplo -T 10  --popsFile ./VCF_processing/pops

It seems some sub function of genomics.py still working on with reporting error below:
Traceback (most recent call last):
  File "/users/shuangyang.wu/miniconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/users/shuangyang.wu/miniconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "popgenWindows.py", line 44, in stats_wrapper
    Aln = genomics.genoToAlignment(window.seqDict(), sampleData, genoFormat = genoFormat)
  File "/groups/dolan/user/shuangyang.wu/software/genomics_general/genomics.py", line 1104, in genoToAlignment
    haploidSeqs.append(forceHomo(seqList[0]))
  File "/groups/dolan/user/shuangyang.wu/software/genomics_general/genomics.py", line 408, in forceHomo
    return [homo(s) for s in sequence]
  File "/groups/dolan/user/shuangyang.wu/software/genomics_general/genomics.py", line 408, in <listcomp>
    return [homo(s) for s in sequence]
  File "/groups/dolan/user/shuangyang.wu/software/genomics_general/genomics.py", line 31, in homo
    def homo(diplo): return diploHomoDict[diplo]
**KeyError: '*'**

For now, I didn't get the results yet, could I ask if this affects the output? Thanks.

Besides, are you also suggesting include the invariant in the vcf for the fst, pi analysis? Thanks

Best,
Shuangyang

**Comment by wushyer** [comment]
Just update: no output since last night. It has been 12 hours with 1m snps.

**Comment by simonhmartin** [comment]
If the job hasn't exited on its own, you will have to kill it yourself, because it has failed.
The problem appears to be an issue with your geno file. I recommend checking whether there are any non-standard genotypes. Alternatively you could try running on a small subset of lines, which would reveal if there is a problem with every input line or only with some of them.

**Comment by wushyer** [comment]
> If the job hasn't exited on its own, you will have to kill it yourself, because it has failed. The problem appears to be an issue with your geno file. I recommend checking whether there are any non-standard genotypes. Alternatively you could try running on a small subset of lines, which would reveal if there is a problem with every input line or only with some of them.

Hi Simon, I appreciated the quick reply. I found some non-AGCTN in the geno file which explain the issue. It works well now! By the way, do you also suggest to include the invariant in the vcf file for pi, dxy, fst analysis? Many thanks

Best,
Shuangyang

**Comment by simonhmartin** [comment]
That's great.
For pi and dxy, you will need to include invariant sites to get correct outputs. For Fst it is not necessary.

**Comment by wushyer** [comment]
> That's great. For pi and dxy, you will need to include invariant sites to get correct outputs. For Fst it is not necessary.

I see. Thanks for all the clarification!
Best,
Shuangyang
