### ISSUE TITLE
How to cite ？

### ISSUE THREAD

**Issue by zy66-su** [simonhmartin/genomics_general#98]
Hi, thank you for providing us with convenience. I calculated Dxy using this script, but how can I cite it in the paper?

**Comment by simonhmartin** [comment]
You can just link to the github page. If you would like to cite work in which that code has been used, you could cite this: https://doi.org/10.1371/journal.pbio.3000610

**Comment by zy66-su** [comment]
> 

Ok, thank you for your reply
